/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package homequest.jframe.Buyer;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author crnc
 */
public class Workspace extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
        java.util.logging.Logger.getLogger(Workspace.class.getName());

    /**
     * Creates new form Main
     */
    public Workspace() {
        initComponents();
        loadUserData();
        setupEventHandlers();
    }

    private void loadUserData() {
        homequest.model.Buyer buyer = homequest.HomeQuest.getBuyer();
        UserName1.setText(buyer.getName());
        UserType1.setText("Buyer");
    }

    private void setupEventHandlers() {
        jButton1.addActionListener(e -> browseAvailableProperties());
        jButton2.addActionListener(e -> requestPurchase());
        jButton3.addActionListener(e -> viewPurchaseHistory());
        jButton4.addActionListener(e -> manageWallet());
        Logout.addActionListener(e -> returnToMain());
    }

    private void browseAvailableProperties() {
        ViewAvailableProperties viewWindow = new ViewAvailableProperties();
        viewWindow.setVisible(true);
        this.dispose();
    }

    private void requestPurchase() {
        PurchaseProperty purchaseWindow = new PurchaseProperty();
        purchaseWindow.setVisible(true);
        this.dispose();
    }

    private void viewPurchaseHistory() {
        ViewPurchaseHistory historyWindow = new ViewPurchaseHistory();
        historyWindow.setVisible(true);
        this.dispose();
    }

    private void manageWallet() {
        homequest.model.Buyer buyer = homequest.HomeQuest.getBuyer();

        String message = String.format(
            "Current Balance: ₱%,.2f\n\nEnter amount to add (or cancel):",
            buyer.getWalletBalance()
        );
        String input = javax.swing.JOptionPane.showInputDialog(
            this,
            message,
            "Wallet Manager",
            javax.swing.JOptionPane.QUESTION_MESSAGE
        );

        if (input != null && !input.trim().isEmpty()) {
            try {
                double amount = Double.parseDouble(input);
                if (amount > 0) {
                    buyer.addFunds(amount);
                    javax.swing.JOptionPane.showMessageDialog(
                        this,
                        String.format(
                            "Funds added successfully!\nNew Balance: ₱%,.2f",
                            buyer.getWalletBalance()
                        ),
                        "Success",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE
                    );
                    UserName1.setText(buyer.getName());
                } else {
                    javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Amount must be positive.",
                        "Invalid Amount",
                        javax.swing.JOptionPane.ERROR_MESSAGE
                    );
                }
            } catch (NumberFormatException e) {
                javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Invalid amount entered.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
                );
            }
        }
    }

    private void returnToMain() {
        homequest.jframe.Main main = new homequest.jframe.Main();
        main.setVisible(true);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Content = new javax.swing.JPanel();
        ButtonWrapper = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        ButtonWrapper2 = new javax.swing.JPanel();
        Logout = new javax.swing.JButton();
        Header1 = new javax.swing.JPanel();
        HeaderLabel1 = new javax.swing.JLabel();
        UserType1 = new javax.swing.JLabel();
        UserName1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 500));

        Content.setMinimumSize(new java.awt.Dimension(562, 279));
        Content.setPreferredSize(new java.awt.Dimension(563, 279));
        java.awt.GridBagLayout ContentLayout = new java.awt.GridBagLayout();
        ContentLayout.columnWidths = new int[] {0};
        ContentLayout.rowHeights = new int[] {0, 5, 0};
        ContentLayout.columnWeights = new double[] {0.0};
        ContentLayout.rowWeights = new double[] {0.0};
        Content.setLayout(ContentLayout);

        ButtonWrapper.setLayout(new java.awt.GridLayout(4, 1, 0, 20));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("Browse Available Properties");
        ButtonWrapper.add(jButton1);

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton2.setText("Purchase Property/s");
        ButtonWrapper.add(jButton2);

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton3.setText("View Purchase History");
        ButtonWrapper.add(jButton3);

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton4.setText("Wallet Balance");
        ButtonWrapper.add(jButton4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        Content.add(ButtonWrapper, gridBagConstraints);

        ButtonWrapper2.setLayout(new java.awt.GridLayout(1, 1, 20, 0));

        Logout.setText("Logout");
        ButtonWrapper2.add(Logout);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        Content.add(ButtonWrapper2, gridBagConstraints);

        Header1.setLayout(new java.awt.GridBagLayout());

        HeaderLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        HeaderLabel1.setText("HomeQuest");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.weightx = 1.0;
        Header1.add(HeaderLabel1, gridBagConstraints);

        UserType1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        UserType1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserType1.setText("Owner");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        Header1.add(UserType1, gridBagConstraints);

        UserName1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        UserName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserName1.setText("Owner Name Here");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        Header1.add(UserName1, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addComponent(Header1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Header1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (
            ReflectiveOperationException
            | javax.swing.UnsupportedLookAndFeelException ex
        ) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Workspace().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonWrapper;
    private javax.swing.JPanel ButtonWrapper2;
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Header1;
    private javax.swing.JLabel HeaderLabel1;
    private javax.swing.JButton Logout;
    private javax.swing.JLabel UserName1;
    private javax.swing.JLabel UserType1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables
}
